First Module Capstone Project Submission
aeh1707/neuromatch-conference-website pull request #1
Opened 2022-05-27 17:45 UTC by aeh1707

This is a responsive website for a neurosience conference. Images and icons are added to suit the subject theme. The keynote speakers section of the home page is generated dynamically in javascript and the mobile menu feature is also implemented.

2022-05-27 20:17 UTC, zieeco requested changes
Hi @aeh1707 


Great work on the capstone project 👏 
You've done well implementing the project, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._


<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>


## Optional suggestions
- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-27 20:17 UTC, zieeco commented on styles.css
> +}
- Please, kindly reduce the width to match the design below:

**your design**

![weight](https://user-images.githubusercontent.com/59397159/170767015-9eebbe1e-488a-44f2-877e-1ba4ae2a4917.png)



**original design**

![theweight](https://user-images.githubusercontent.com/59397159/170767008-0d3ca31d-30f0-42b6-9c64-3ec03ce9ffac.png)

2022-05-27 20:17 UTC, zieeco commented on styles.css
> +  }
- [x]  Please, kindly reduce the spaces to match the design as much as possible below:
- [x] Also, add the remaining nav items to match the design. Remember you're making a clone of an existing website so you should try as much as possible to add what you see except the content that is meant to be personalized.
- [x] Kindly add some more padding to your register button to match the design's button below:
- [x] KIndly increase the spaces between each nav item to match the design as much as you can below:
- [x] Kindly add the active color to the `About` when a user clicks on it to indicate that the user is on the about page to improve the user experience.

**original design**

![padding and missing](https://user-images.githubusercontent.com/59397159/170767850-4770124f-fa3d-416f-b955-102bd099ca37.png)

**your design**
![misign and padding](https://user-images.githubusercontent.com/59397159/170767856-d78fceaf-74e6-4d89-9ec0-c1b57bb2badb.png)

2022-05-27 20:17 UTC, zieeco commented on styles.css
> +
- Please, kindly use the correct background color as in the design which is #f7f7f7 to match the design below: 


**your background color**
![cc3](https://user-images.githubusercontent.com/59397159/170769990-49da5028-c216-489b-9077-f2e4ef807bea.png)

**original background color**
![ccolor](https://user-images.githubusercontent.com/59397159/170769996-dbfa6fed-2974-4978-abba-c59e7a9a1852.png)

2022-05-27 20:17 UTC, zieeco commented on styles.css
> +  }
- Please let's use the correct color which is #515151: to match the design as much as possible below:

**your color**
![dark](https://user-images.githubusercontent.com/59397159/170771180-111444ab-c4e2-49ea-b5f1-d74bdd7fd555.png)

**design color**
![dark2](https://user-images.githubusercontent.com/59397159/170771167-e1f4fbf5-804e-40b1-a0c1-6231b60b9869.png)

2022-05-27 20:17 UTC, zieeco commented on styles.css
> +  }
- Please, let's use the correct font size on the second content and space between the two contents to match the design as much as possible below:


**your font size on second content**
![f-s](https://user-images.githubusercontent.com/59397159/170771710-62de89e1-ac48-43db-a37e-2b77c9ac160d.png)

**foriginal font size  and space on second content**
![f-se](https://user-images.githubusercontent.com/59397159/170771704-c1819a6a-d98c-4c6c-a9fa-650cfe375942.png)

2022-05-27 20:17 UTC, zieeco commented on styles.css
> +  }
- Please, try to reduce the min-width to match the design as now the space before the `our goal` Is too much and doesn't match the design yet below:


**design space**
![spax](https://user-images.githubusercontent.com/59397159/170773972-5a2a9e2b-33be-4aa2-8d69-49e68486a477.png)

**your space**
![space](https://user-images.githubusercontent.com/59397159/170773976-a6aabf4b-5fef-4211-adb9-821785c1905f.png)

2022-05-27 20:17 UTC, zieeco commented on styles.css
> +}
- Please, try to reduce the min-width to match the design as now the space before the `our goal` Is too much and doesn't match the design yet below:


**design space**
![spax](https://user-images.githubusercontent.com/59397159/170773972-5a2a9e2b-33be-4aa2-8d69-49e68486a477.png)

**your space**
![space](https://user-images.githubusercontent.com/59397159/170773976-a6aabf4b-5fef-4211-adb9-821785c1905f.png)

2022-05-27 20:17 UTC, zieeco commented on styles.css
> +
- Please, kindly add the remaining card and reduce the spaces to match the design as yours is not complete yet below:
- Please, use the same background color for each card according to the design.
- Reduce the height of each cards according to the design.
- Please, ensure the content on the cards is clear enough to improve the user experience.
- Please, kindly use the same background color of the parent container to match the design as much as you can

**your card and space**
![complete](https://user-images.githubusercontent.com/59397159/170774702-dde34f6f-7ea6-4a74-bc83-8acac3c3ecf6.png)

**orighnal card and space**
![completee](https://user-images.githubusercontent.com/59397159/170774713-f03271da-c6da-410d-89ab-d78fc9e054d8.png)

2022-05-27 20:17 UTC, zieeco commented on styles.css
> +}
- Hey, you're doing great but please bear in mind that you're making a clone of an existing website. we should try making a complete clone as much as possible except for the content we're allowed to be personalized. Please kindly follow the design pattern on this element according to the design below:

**your implementation**
![replace](https://user-images.githubusercontent.com/59397159/170776362-fadb9c4f-d1ac-4166-882b-2cce02ec2170.png)

**design inplementation**
![rep](https://user-images.githubusercontent.com/59397159/170776356-43f79dc2-c46d-40aa-999e-2ee359aa40d0.png)

2022-05-27 20:17 UTC, zieeco commented on styles.css
> +
- Please, kindly add another speaker to match the design as yours is 5 remain one to complete 6
- Please, kindly reduce the margin-left and margin-right as your's is in the center but on the design, it's not in the center
- Please, kindly use the same color according to the design as much as you can

**6**
![kfea](https://user-images.githubusercontent.com/59397159/170777253-02ea3d28-6f7f-4bcc-9c78-e83165476131.png)

**5**
![keynote](https://user-images.githubusercontent.com/59397159/170777258-800e3399-4f7c-4b0f-bb8d-59c160dc8a19.png)

2022-05-27 20:17 UTC, zieeco commented on styles.css
> +
- [x] Please let's stick to the background color according to the design as much as possible.
- [x] Please let's stick to the color of each logo by adding opacity according to the design as much as possible.
- [x] Please let's stick to the width of each logo size according to the design as much as possible.
- [x] Please kindly reduce the padding of the partner's container to match the design as much as we can

**your design**
![widthhh](https://user-images.githubusercontent.com/59397159/170778336-0398ffdc-6fa9-4b17-a90f-cf1ca07d69d5.png)

**original design**
![widthh](https://user-images.githubusercontent.com/59397159/170778339-84602d47-5ddf-4a43-822f-25559090d7b2.png)

2022-05-27 20:17 UTC, zieeco commented on styles.css
> +  }
- Please let's use the right color of the footer element as much as we can to match the design below:


**original design**
![collll](https://user-images.githubusercontent.com/59397159/170779516-b61d6c76-1d8f-435e-a983-b94d0a44ddb4.png)

**your design**
![colll](https://user-images.githubusercontent.com/59397159/170779518-ceafc2ba-eea4-4bbb-a5c6-9284d3252375.png)

2022-05-27 20:17 UTC, zieeco commented on styles.css
> +  }
- [ ] Please, kindly remove this text content as it's not part of the about page in the original design below:

**original about page**
![here](https://user-images.githubusercontent.com/59397159/170780475-37dec77f-20a1-498b-8fd6-b2334c44e471.png)

**you about page**
![r](https://user-images.githubusercontent.com/59397159/170780468-40968d75-9007-4227-92b4-e2b141011dca.png)

2022-05-27 20:17 UTC, zieeco commented on styles.css
> +  }
- Please, let's use the correct background color as used in the design as much as we can below: 

**your background color**
![bk](https://user-images.githubusercontent.com/59397159/170781072-05ec865f-4a7d-4874-aef3-8f9efab3e5e1.png)


**descign background color**
![bk2](https://user-images.githubusercontent.com/59397159/170781067-ab2aad64-fec2-40eb-8628-5ecc81db8c13.png)

2022-05-27 20:17 UTC, zieeco commented on styles.css
> +
- [ ] Please, let's update the team section by adding more content following the design pattern according to the design as much as we can below:

**original section implementation pattern**
![hett](https://user-images.githubusercontent.com/59397159/170781839-a981ae68-63de-4075-abc3-85e69821e237.png)


**your design implementation pattern**
![designn](https://user-images.githubusercontent.com/59397159/170781841-ca898e12-6751-4b51-821e-4994c4ef80ce.png)

2022-05-27 20:17 UTC, zieeco commented on styles.css
> +}
- Please let's use the original background color according to the design which is #2E2E2E

2022-05-27 20:17 UTC, zieeco commented on index.html
> +            </div>
- [ ] Hey, the speaker section should be added dynamically using javascript according to the project requirement. Please, kindly update these changes to meet the project requirement :pray:

2022-05-28 08:35 UTC, phelian23 approved these changes
Hi @aeh1707, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-28 08:36 UTC, merged